import fs from "fs";
import path from "path";

// Paths
const inputPath = path.join(process.cwd(), "tickers/all/allTickers.txt");
const outputPath = path.join(process.cwd(), "src/data/allTickers.ts");

// Read tickers
const tickers = fs
  .readFileSync(inputPath, "utf-8")
  .split("\n")
  .map((t) => t.trim())
  .filter((t) => t.length > 0);

// Generate TypeScript content
const tsContent = `//Auto-generated by scripts/generateTickerSet.ts

export const allTickers = new Set<string>([
${tickers.map((t) => `  "${t}"`).join(",\n")}
]);
`;

// Ensure output directory exists
fs.mkdirSync(path.dirname(outputPath), { recursive: true });

// Write output
fs.writeFileSync(outputPath, tsContent, "utf-8");

console.log(`Successfully generated ${outputPath} with ${tickers.length} tickers.`);
