name: Download Latest Stocks

on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies and jq
        run: |
          sudo apt-get install jq -y
          npm ci

      - name: Create directories
        run: |
          mkdir -p tickers/nasdaq
          mkdir -p tickers/nyse
          mkdir -p tickers/amex
          mkdir -p tickers/all

      - name: Download NASDAQ tickers
        run: |
          curl -L -H "Accept: application/json" \
               -H "Origin: https://www.nasdaq.com" \
               -H "Referer: https://www.nasdaq.com/" \
               -A "Mozilla/5.0" \
               "https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=2000&offset=0&exchange=nasdaq&download=true" \
               --http1.1 -o tickers/nasdaq/nasdaq.json

          cat tickers/nasdaq/nasdaq.json | jq '[.data.rows[].symbol]' > tickers/nasdaq/tickers.json
          cat tickers/nasdaq/tickers.json | jq -r '.[]' > tickers/nasdaq/tickers.txt

      - name: Download NYSE tickers
        run: |
          curl -L -H "Accept: application/json" \
               -H "Origin: https://www.nasdaq.com" \
               -H "Referer: https://www.nasdaq.com/" \
               -A "Mozilla/5.0" \
               "https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=2000&offset=0&exchange=nyse&download=true" \
               --http1.1 -o tickers/nyse/nyse.json

          cat tickers/nyse/nyse.json | jq '[.data.rows[].symbol]' > tickers/nyse/tickers.json
          cat tickers/nyse/tickers.json | jq -r '.[]' > tickers/nyse/tickers.txt

      - name: Download AMEX tickers
        run: |
          curl -L -H "Accept: application/json" \
               -H "Origin: https://www.nasdaq.com" \
               -H "Referer: https://www.nasdaq.com/" \
               -A "Mozilla/5.0" \
               "https://api.nasdaq.com/api/screener/stocks?tableonly=true&limit=2000&offset=0&exchange=amex&download=true" \
               --http1.1 -o tickers/amex/amex.json

          cat tickers/amex/amex.json | jq '[.data.rows[].symbol]' > tickers/amex/tickers.json
          cat tickers/amex/tickers.json | jq -r '.[]' > tickers/amex/tickers.txt

      - name: Combine all tickers
        run: |
          cat tickers/amex/tickers.txt tickers/nyse/tickers.txt tickers/nasdaq/tickers.txt \
            | sort -u > tickers/all/allTickers.txt

      - name: Generate allTickers.ts
        run: npx ts-node-esm scripts/generateTickerSet.ts

      - name: Commit and push tickers and TS set
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add tickers/ src/data/allTickers.ts
          git commit -m "Update tickers and regenerate allTickers.ts" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/AkhilGovan/MarketMood.git
